### ISSUE TITLE
Rotating highlighter bug

### ISSUE THREAD

**Issue by 1001QAdotNET** [stevencohn/OneMore#113]
**Describe the bug**
For the below page the marker does not seem to work properly

**To Reproduce**
select all the text on the page
apply the marker
the highlighter will be applied to just a part of the text

**Expected behavior**
I expect the entire text to get hightlighted

```
<one:Page xmlns:one="http://schemas.microsoft.com/office/onenote/2013/onenote" ID="{xxxxxx}" name="Rollingover marker bug" dateTime="2020-12-08T10:32:06.000Z" lastModifiedTime="2020-12-08T10:33:02.000Z" pageLevel="1" isCurrentlyViewed="true" selected="partial" lang="en-US">
  <one:QuickStyleDef index="0" name="PageTitle" fontColor="automatic" highlightColor="automatic" font="Calibri Light" fontSize="20.0" spaceBefore="0.0" spaceAfter="0.0" />
  <one:QuickStyleDef index="1" name="p" fontColor="automatic" highlightColor="automatic" font="Calibri" fontSize="11.0" spaceBefore="0.0" spaceAfter="0.0" />
  <one:PageSettings RTL="false" color="automatic">
    <one:PageSize>
      <one:Automatic />
    </one:PageSize>
    <one:RuleLines visible="false" />
  </one:PageSettings>
  <one:Title lang="en-US">
    <one:OE alignment="left" quickStyleIndex="0">
      <one:T><![CDATA[Rollingover marker bug]]></one:T>
    </one:OE>
  </one:Title>
  <one:Outline selected="partial">
    <one:Position x="36.0" y="86.4000015258789" z="0" />
    <one:Size width="540.0" height="83.00771331787109" />
    <one:OEChildren selected="partial">
      <one:OE alignment="left" quickStyleIndex="1" style="font-family:Calibri;font-size:12.0pt;color:#24292E">
        <one:T><![CDATA[An event automatically triggers the&nbsp;<span style='font-style:italic'>workflow</span>, which contains a&nbsp;<span style='font-style:italic'>job</span>. The job then uses&nbsp;<span style='font-style:italic'>steps</span>&nbsp;to control the order in which&nbsp;<span style='font-style:italic'>actions</span>&nbsp;are run. ]]></one:T>
      </one:OE>
      <one:OE alignment="left" quickStyleIndex="1">
        <one:T><![CDATA[]]></one:T>
      </one:OE>
      <one:OE alignment="left" quickStyleIndex="1">
        <one:T><![CDATA[]]></one:T>
      </one:OE>
      <one:OE alignment="left" quickStyleIndex="1">
        <one:T><![CDATA[]]></one:T>
      </one:OE>
      <one:OE alignment="left" quickStyleIndex="1" selected="partial">
        <one:T selected="all"><![CDATA[]]></one:T>
      </one:OE>
    </one:OEChildren>
  </one:Outline>
</one:Page>
```

**Comment by stevencohn** [comment]
FYI I fixed a bug in the way the highlighter works across empty lines. But it can't work as I think you might expect. Given this:

```
line1: something
line2:
line3: something more
```

Then line1 and line3 will be highlighted but not line2. This is because OneNote removes styling of empty lines. There's nothing I can do about that.

Not yet released but will be soon...

**Comment by 1001QAdotNET** [comment]
I never encountered that situation, for that case I would highlight each line in particular and as you know I remove the empty lines :-)
The above bug seems to depend on the CDATA or something because in the same doc the highlighter works and it doesnt

**Comment by stevencohn** [comment]
Understood. I wanted to point out the empty line problem because your sample page only had the last empty line selected.

**Comment by CLITrees** [comment]
still not working see the gif; the XML is the above one
![rollover highlighter](https://user-images.githubusercontent.com/67560397/102001459-85bbd900-3cc0-11eb-85a2-65e7b6c562d8.gif)

**Comment by CLITrees** [comment]
This is if I apply the highlighter to the same text again and again and again, you can see incremental highlighting with every run of the command 
![rollover highlighter3](https://user-images.githubusercontent.com/67560397/102001515-33c78300-3cc1-11eb-91a1-74686068a9cf.gif)

**Comment by 1001QAdotNET** [comment]
This is if I apply the highlighter to the same text again and again and again, you can see incremental highlighting with every run of the command 
![rollover highlighter3](https://user-images.githubusercontent.com/67560397/102001515-33c78300-3cc1-11eb-91a1-74686068a9cf.gif)

**Comment by stevencohn** [comment]
I can reproduce this. I'll fix it.

**Comment by stevencohn** [comment]
https://github.com/stevencohn/OneMore/releases/tag/3.10.1

**Comment by 1001QAdotNET** [comment]
This can be closed testing shows it works as expected
