### ISSUE TITLE
Cannot import Markdown files

### ISSUE THREAD

**Issue by cplager** [stevencohn/OneMore#1566]
# Problem to Solve

Unable to import Markdown file

# To Reproduce

more...file...import, then chose markdown file
 
# Expected Behavior

Expects to load Markdown to formatted OneNote

# Screenshots

# Environment (if applicable)

Off365 OneNote
Latest OneMore

Log file attached.

```
16|03:01:41.838| Running command ImportCommand
16|03:01:52.344| ..importing markdown C:\Users\cplag\Downloads\readme.md
16|03:01:52.393| ..System.TypeLoadException
Message: Could not load type 'System.Numerics.Vector`1' from assembly 'System.Numerics.Vectors, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
Source: System.Memory
```

# Additional Context

Add any other context about the problem here. Attach page XML file or the app log file as appropriate. You can find the log file here: %localappdata%\temp\OneMore.log

THE FINE PRINT This is a hobby project that I started for myself. I'm happy to take requests and will promise to
consider each one carefully but offer no guarantees that I will ultimately agree to their
usefulness or have time to implement any of them. If OneNote offers a "close enough" work-around
then I will probably reject the request - you've been warned!

[OneMore.log](https://github.com/user-attachments/files/16830201/OneMore.log)

**Comment by cplager** [comment]
I get the same error if I try converting text to Markdown using **more->Edit->Convert Markdown**

**Comment by stevencohn** [comment]
Which version of OneMore are you running? It should have been fixed in [6.5.1](https://github.com/stevencohn/OneMore/releases/tag/6.5.1) by https://github.com/stevencohn/OneMore/issues/1538, although this is not a recommended version due to the critical issue explained with table formulas. If you're skipping 6.5.1 because of that, then the subsequent release will also have the patch.

**Comment by cplager** [comment]
I'm running 6.5.0. I can wait until you release a recommended version with
the fix. Thanks!

**Comment by cplager** [comment]
**Update**  I am already running 6.5.1 (not 6.5.0)
```
Version 6.5.1 with OneNote 16.0.17928.20114
```

**Comment by swiwchar** [comment]
I am running **Version 6.6.1 with OneNote 16.0.17328.20670** and still get this 'Error running command ConvertMarkdownCommand.'

`01|01:42:04.476| Starting dllhost 39116, 2496 Mhz, 64 MB, en-US/en-US, v6.6.1, OneNote 15.0, Office 16.0, 2024-12-19 13:42
01|01:42:04.476| ..Windows 11 Enterprise, Version 23H2, Build 22621, 64 bit
01|01:42:04.491| ..C:\Program Files\Microsoft Office\root\Office16\ONENOTE.EXE (16.0.17328.20670)
01|01:42:04.507| ..OnConnection(ConnectionMode:ext_cm_Startup,custom[1:Int32])
01|01:42:04.507| ..OneAddInsUpdate(custom[])
01|01:42:05.072| ..building ribbon
01|01:42:05.082| ..building ribbon colorizer commands
01|01:42:05.248| ..building ribbon language proofing commands
01|01:42:05.249| ..building ribbon groups
01|01:42:05.249| ..building context menu
01|01:42:05.341| ..OnStartupComplete(custom[])
01|01:42:05.352| ..starting command service
01|01:42:05.352| ..starting reminder service
01|01:42:05.353| ..starting navigation service
01|01:42:05.353| ..hashtag service is disabled
01|01:42:05.353| ..ready
09|01:42:06.007| defined 52 hotkeys for input locale 1033

**14|01:42:39.754| Running command ConvertMarkdownCommand
13|01:42:40.005| Error running command ConvertMarkdownCommand
13|01:42:40.005| System.TypeLoadException
Message: Could not load type 'System.Numerics.Vector' from assembly 'System.Numerics.Vectors, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.**
Source: System.Memory
StackTrace:    at System.SpanHelpers.SequenceEqual(Byte& first, Byte& second, NUInt length)
   at System.MemoryExtensions.Equals(ReadOnlySpan`1 span, ReadOnlySpan`1 other, StringComparison comparisonType)
   at Markdig.Helpers.CompactPrefixTree`1.TryMatchExact(ReadOnlySpan`1 text, KeyValuePair`2& match)
   at Markdig.Parsers.HtmlBlockParser.TryParseTagType16(BlockProcessor state, StringSlice line, Int32 startColumn, Int32 startPosition)
   at Markdig.Parsers.HtmlBlockParser.MatchStart(BlockProcessor state)
   at Markdig.Parsers.HtmlBlockParser.TryOpen(BlockProcessor processor)
   at Markdig.Parsers.BlockProcessor.TryOpenBlocks(BlockParser[] parsers)
   at Markdig.Parsers.BlockProcessor.TryOpenBlocks()
   at Markdig.Parsers.BlockProcessor.ProcessLine(StringSlice newLine)
   at Markdig.Parsers.MarkdownParser.ProcessBlocks(BlockProcessor blockProcessor, String text)
   at Markdig.Parsers.MarkdownParser.Parse(String text, MarkdownPipeline pipeline, MarkdownParserContext context)
   at River.OneMoreAddIn.Commands.OneMoreDig.ConvertMarkdownToHtml(String path, String markdown)
   at River.OneMoreAddIn.Commands.ConvertMarkdownCommand.<Execute>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at River.OneMoreAddIn.CommandFactory.<Run>d__6.MoveNext()
TargetSite: [System.Memory] System.SpanHelpers::SequenceEqual()
`

**Comment by stevencohn** [comment]
Likely fixed by 7.0 Wix installer, but this is also old with no new updates so closing
